### ISSUE TITLE
Swagger UI encounters 404 errors when upgrading to an API project

### ISSUE THREAD

**Issue by zsharp-gls** [dotnet/systemweb-adapters#284] opened 2023-02-08 21:52 UTC
### Describe the bug
An API project created through the Upgrade process will have Swagger configured, but the SwaggerUI endpoint encounters 404 errors for necessary files, like `swagger-ui.css` or `swagger-ui-standalone-preset.js`.

### To Reproduce
A repro is available at [this GitHub repo](https://github.com/zsharp-gls/SystemWebAdapters-Swagger). I took the following steps:

- Set up a .NET Framework 4.7.2 ASP.NET app
- Use the Migration Extension to add a new .NET 6.0 API project
- Start the projects. It should default to the `/swagger/index.html` page, resulting in 404 errors

### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*:
- Technologies and versions used (i.e. MVC/WebForms/etc): MVC
- .NET Framework Version: 4.7.2
- IIS Version: 10.0.19041.1
- Windows Version: 10

*ASP.NET Core Application*:
- Targeted .NET version: .NET 6.0
- .NET SDK version: I have a number of SDKs installed, including 6.0.401 with 7.0.102 as the latest

**Comment by joperezr** [comment] 2023-02-08 22:00
This requires a bit more investigation, thanks for providing a repro. Seems like the issue is that some file is just not getting served correctly, potentially a problem with Yarp? We will take a closer look.

**Comment by joperezr** [comment] 2023-02-08 22:03
@Tratcher mentioned that it seems like we are potentially running into this: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2599

**Comment by zsharp-gls** [comment] 2023-02-08 22:14
Thanks! The workaround described there works for my real-world need and my repro ([in the workaround branch](https://github.com/zsharp-gls/SystemWebAdapters-Swagger/tree/workaround))

One thing I noticed is that the issue above is talking about just .NET 7.0, but my repro is .NET 6.0

**Comment by joperezr** [comment] 2023-02-15 21:43
Thanks for checking @zsharp-gls and glad that it worked. Given this is an external issue, we'll go ahead and close this here.

**Closed by joperezr** 2023-02-15 21:43 UTC
