### ISSUE TITLE
Ask About HttpCachePolicy and HttpResponse.Cache

### ISSUE THREAD

**Issue by Clounea** [dotnet/systemweb-adapters#369] opened 2023-07-12 09:19 UTC
## Summary

HttpCachePolicy and HttpResponse.Cache are missing in .NetCore. I want to ask if there are equivalents and if there is plan to add them to adapter.

## Motivation and goals
We need migrate code (an API in Sharepoint) to ASP.NetCore and we find that the APIs are not supported by ASP.NetCore. 

## In scope
- HttpCachePolicy.SetLastModified
- HttpCachePolicy.SetMaxAge
- HttpCachePolicy.SetOmitVaryStar
- HttpCachePolicyBase.VaryByHeaders
- HttpCacheVaryByHeaders.Item
- HttpResponse.Cache

## Examples
1. ServerAndPrivate cache settings 
```C#
// cache settings: do not cache in the client, cache in the server. Give client timestamp.
HttpCachePolicy cache = context.Response.Cache
cache.SetCacheability(HttpCacheability.ServerAndPrivate);
cache.SetLastModified(context.Timestamp);
cache.SetExpires(context.Timestamp.AddDays(-1));
cache.SetMaxAge(TimeSpan.FromSeconds(0));
cache.SetOmitVaryStar(true);
```

2. set VaryByHeaders
```C#
httpContext.Response.Cache.VaryByHeaders["Origin"] = true;
```

**Comment by twsouthwick** [comment] 2023-07-12 16:47
I believe the best ASP.NET Core equivalent would be [output caching](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/overview?view=aspnetcore-7.0#output-caching). Can you take a look and see if that would work for your scenario? If so, we could take a PR that implements HttpCachePolicy against them.

**Comment by twsouthwick** [comment] 2023-07-12 16:47
Duplicate of #155

**Comment by Clounea** [comment] 2023-07-14 09:16
I tried the branch.
And I found that it lacks 2 APIs
1. `HttpCachePolicy.SetExpires`  Does Expires still work in ASP.NetCore?
2. `HttpResponseBase.Cache`

**Comment by Clounea** [comment] 2023-07-26 08:29
I test the latest branch and it works fine

**Closed** 2023-07-26 16:54 UTC
Labels: needs author feedback, In-PR
