### ISSUE TITLE
webforms migration

### ISSUE THREAD

**Issue by wallym** [dotnet/systemweb-adapters#42] opened 2022-05-24 19:51 UTC
I've got an asp .net webforms app.  There are probably 40 webforms pages, but only a couple of really big webforms pages.  The app uses ado.net datasets/datatables for database access to sql server and a little bit to mysql.  The app pretty much uses simple stuff in webforms, but does use the updatepanel/updateprogress, but nothing from the ajax control toolkit.  I use some basic session state, but not a lot.  We are trying to figure out how to migrate to asp .net core (I understand that this is a manual conversion and one page at a time).  All of the talk in this is about migrating from asp .net mvc.  Has anyone updated a webforms app with this tool?  Is updating with webforms possible?

TIA.

**Comment by wallym** [comment] 2022-05-24 19:52
And if there is a better place to ask questions about migration, just point me to that.

**Comment by twsouthwick** [comment] 2022-05-25 18:31
@wallym Thanks for the issue. The general idea this project is proposing was actually initially developed with Webforms in mind as well. The pattern we're pushing for migration is to identify what a *route* is for a given technology; for WebForms, it is most likely a page. So, given that, you should be able to migrate a page at a time.

The target technology isn't as straightforward as MVC, but we've seen success with moving to Blazor. It has the most similar AppModel, but it is definitely a different beast that requires a bit of tweaking. This project specifically helps when you have business logic that you're relying on in additional libraries that can be moved over a little bit easier.

Can you share a bit of the structure of a page? Feel free to remove any proprietary stuff - it's more interesting to see how much code you are doing in the code behind and things of that sort.

**Comment by slipgateio** [comment] 2022-05-30 05:04
I can confirm WebForms works, I've only had time to do some extremely limited testing, but I ran the migration on my WebForms app, migration completed, I was able to run the .NET Core MVC project, then navigate to my WebForms login page.

**Comment by davidfowl** [comment] 2022-05-30 05:34
@wallym Nothing in this repo helps you migrate your webforms app to ASP.NET Core. It lets you add new pages or migrated existing sections of your site to ASP.NET Core incrementally. Migrating the webforms content itself, the most logical choice would be to move to something like Razor Pages. You still still need to do all the hard work to move away from the update panel, view state, webcontrols etc. There's no smooth migration path from webforms on ASP.NET Core.

**Comment by birojnayak** [comment] 2022-06-01 03:42
@davidfowl @twsouthwick I started reading this project thinking that it provides porting for Webform(aspx/aspx.cs) => to Aspnet.core or at least enable it to run in aspnet.core(with no platform incompatibility and no mono route)...  I assume this is not, it's mostly the routing and http context ? Please clarify if my understanding is incorrect and if there is route for above..

**Comment by davidfowl** [comment] 2022-06-01 04:06
@birojnayak no, this project does not do that. There's no migration path to webforms on .NET Core/6+ as described here https://github.com/dotnet/systemweb-adapters/issues/42#issuecomment-1140717966.

These adapters are to enable code sharing logic that uses `System.Web.HttpContext`. Hopefully this [blog post](https://devblogs.microsoft.com/dotnet/incremental-asp-net-to-asp-net-core-migration/) gives more context.

**Comment by birojnayak** [comment] 2022-06-01 04:55
@davidfowl yeah I assumed that.. if there is an opportunity for web forms which can ported as is(like WCF=>CoreWCF) we would be happy to help.. as there is no direct path other than re-write, which many times not an option for our customers...

**Comment by davidfowl** [comment] 2022-06-01 05:21
> @davidfowl yeah I assumed that.. if there is an opportunity for web forms which can ported as is(like WCF=>CoreWCF) we would be happy to help.. as there is no direct path other than re-write, which many times not an option for our customers...

Good to know. Unfortunately because WebForms is to intertwined with IIS and the CLR hosting APIs making something like CoreWCF would be highly incompatible and we have no plans to move it forward as a technology outside of the existing windows .NET Framework environment.

**Comment by conficient** [comment] 2022-06-01 05:56
I'm using the [Cocoon](https://github.com/VisualReCode/Cocoon) project to port a WebForms app; it operates in a similar way to this app, except it supports Blazor, which is the most natural migration path for a WebForm user. This project will hopefully support Blazor soon.

It won't convert any pages, but the Blazor component model is very similar to WebForms and you'll find migration to that model (especially Blazor Server) is easier than MVC or RazorPages.

More info [here](https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/). Jeff Fritz also has a project https://github.com/FritzAndFriends/BlazorWebFormsComponents that helps too.

**Comment by davidfowl** [comment] 2022-06-05 20:12
@birojnayak Turns out this company has a webforms port on top of ASP.NET Core https://devblogs.microsoft.com/dotnet/incremental-asp-net-to-asp-net-core-migration/#comment-15756. That's worth a follow up.

**Comment by jbennink** [comment] 2022-06-09 08:56
> What is you setup. I have a webforms app that after running Project Migration If I start that project it runs withou adding yarp stuff. What @mike Rousos showed on youtube was not how it works with webforms. When I start the new Core app and navigate to my old aspx [pages I get a 502 Bad gateway. From his video it looks like you should start you old project and that bootstraps the whole thing although that feels strange and starting the Core one feels logical!

Update: A fresh webforms app does work as shown in the video and as confirmed by @slipgateio so I will have to dig deeper into my problem.

**Comment by jbennink** [comment] 2022-06-09 09:22
Update2: However switching to my project and back it did not work. And now in VS2022 Preview I don't see the Migration optiion. It's not under Installed extensions, but when I check online it does have a green check :-| preview bits...
I also have the regular VS2022 Community and had installed it there too. It does show under installed there but still the project does not give me the Project Migration option.

I saw the extension again, then disabled it and restarted VS2022 Preview and then I got this popup.
![image](https://user-images.githubusercontent.com/49071903/172812811-9d89010c-2cd7-408e-919f-8d6c7630f725.png)

Next I will try uninstall reinstall. 

Background info: Initially I installed it on my VS2022 Community. Then I created a default ASPNET app to test a simple scenario (which I did in VS2022 Preview so I had to install the extension there as well. After the restart of VS2022 Preview that project migrated and ran. But after shutting down VS and trying it again with my real-world app on the VS2022 Community (without success) and TEHN returning to VS2022 Preview with my simple app it did not work.

**Comment by jbennink** [comment] 2022-06-09 09:59
Update3: Not sure whether this is the place to post this BUT:

A migrated a new clean project again and everything works fine. Multiple starts. 

*BUT*

When I mark the old Webforms project as startup project in visual studio, then starting with F5 does not bootstrap the Core project anymore and simply starts my old net48 webforms project.

I was baffled at first until I realised the extension set both projects to start. which is also indicated by the solution node being bold and not the single startup project. So to restore this behaviour select the solution nod and right-click "Set startup projects" and choose multiple startup projects (again) and have both set to start.

This makes me wonder how you should deploy this to IIS ?

**Comment by jbennink** [comment] 2022-06-09 11:11
Update4: A bit ashamed. After going back to my solution the problems seems to have been that I was not launching multiple projects 👎 So it's working for my webforms as well...with an empty net6.0 project. Now the conversion work can start :-)

**Comment by birojnayak** [comment] 2022-06-10 22:44
> @birojnayak Turns out this company has a webforms port on top of ASP.NET Core https://devblogs.microsoft.com/dotnet/incremental-asp-net-to-asp-net-core-migration/#comment-15756. That's worth a follow up.

@davidfowl have you folks initiated the discussion loop me in biroj@ else let me know I would be happy to initiate the discussion...

**Comment by Michelh91** [comment] 2022-06-24 22:45
> I'm using the [Cocoon](https://github.com/VisualReCode/Cocoon) project to port a WebForms app; it operates in a similar way to this app, except it supports Blazor, which is the most natural migration path for a WebForm user. This project will hopefully support Blazor soon.
> 
> It won't convert any pages, but the Blazor component model is very similar to WebForms and you'll find migration to that model (especially Blazor Server) is easier than MVC or RazorPages.
> 
> More info [here](https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/). Jeff Fritz also has a project https://github.com/FritzAndFriends/BlazorWebFormsComponents that helps too.

Do you have any sample using Cocoon to reverse proxy between webforms and blazor?

Having a hard time figuring out how to implement that solution

**Comment by conficient** [comment] 2022-06-27 16:17
@Michelh91 I use the techniques documented in the [Cocoon repository documentation](https://github.com/VisualReCode/Cocoon) that show how it's done. There are sample applications using a WebForms back-end [here](https://github.com/VisualReCode/Cocoon/tree/develop/samples). Mark has sample Blazor WASM and Blazor Server clients which use the `Wingtip-Toys` WebForms app as the sample site.

**Comment by conficient** [comment] 2022-06-27 16:24
@Michelh91 feel free to message me directly, or raise and issue on the Cocoon site if you're having issues with it.

**Comment by Michelh91** [comment] 2022-06-27 21:25
Wow, didnt see the samples in Cocoon's github.

I cloned and got them working :) going to play a bit now to try to integrate my webforms app with it.

Thank you so much!

> @Michelh91 I use the techniques documented in the [Cocoon repository documentation](https://github.com/VisualReCode/Cocoon) that show how it's done. There are sample applications using a WebForms back-end [here](https://github.com/VisualReCode/Cocoon/tree/develop/samples). Mark has sample Blazor WASM and Blazor Server clients which use the `Wingtip-Toys` WebForms app as the sample site.

**Comment by GerardSmit** [comment] 2022-09-27 09:08
FYI, there is a community project called `systemweb-adapters-ui` which is being developed by @twsouthwick: https://github.com/twsouthwick/systemweb-adapters-ui which uses the open-source WebForms code from https://github.com/Microsoft/referencesource/ and this project (`systemweb-adapters`).

**Comment by birojnayak** [comment] 2022-09-27 16:37
@GerardSmit thanks for the update.. @twsouthwick I will ping you in the original project repo...

**Comment by twsouthwick** [comment] 2022-09-27 16:40
Please note that that project is an experiment to explore what it would take to support webforms. That said, happy to see what people think

**Comment by birojnayak** [comment] 2022-09-27 17:01
> Please note that that project is an experiment to explore what it would take to support webforms. That said, happy to see what people think

@twsouthwick everything starts with small experiment

**Comment by danroth27** [comment] 2023-06-28 20:53
We support incrementally migrating ASP.NET Web Forms apps to alternative technologies like ASP.NET Core MVC or even Blazor, but we don't plan to provide direct support for Web Forms through the adapters. Closing.

**Closed by danroth27** 2023-06-28 20:53 UTC
